# Generated by Django 3.1.7 on 2021-03-29 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('code', models.CharField(max_length=100)),
                ('limit', models.IntegerField()),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(default=None)),
                ('status', models.CharField(choices=[('deactivated', 'Deactivated'), ('activated', 'Activated')], default='deactivated', max_length=100)),
                ('instruction', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
